Google Colab integration
vintasoftware/entity-embed pull request #22
Opened 2021-04-13 18:49 UTC by rvlb

2021-04-22 19:32 UTC, fjsj requested changes
- Could you please make a Colab for notebooks/End-to-End-Matching-Example.ipynb?
- Please also check all links inside the Colab notebooks.

2021-04-22 19:34 UTC, fjsj commented
Also, in the examples section in readme, please make a table like this with colab links: https://github.com/KevinMusgrave/pytorch-metric-learning/blob/master/examples/README.md

2021-04-22 19:57 UTC, fjsj commented
One more thing: is there a way to force Colab to use a GPU? I had to manually use "Change runtime type" to use a GPU.

2021-04-22 20:00 UTC, rvlb commented
Not that I've found, pytorch-metric-learning also asks that we do it manually

Our readme: https://github.com/vintasoftware/entity-embed/blob/5f3b34e8b42bbed4f621a1c5a37edf7de75e5509/notebooks/google-colab/README.md

2021-04-22 20:06 UTC, fjsj commented
- Please keep the current descriptions we have in README for the examples.
- Make a Colab for notebooks/End-to-End-Matching-Example.ipynb. Not sure how to load the model though, maybe we'll have to pre-generate it. Please research if possible to have disk persistence in Colab across Notebooks.
- If it's not possible to programatically request a GPU, then please add the instruction to the top of the Colab Notebook.

2021-04-23 18:13 UTC, rvlb commented
Persistence seems to be possible via Google Drive integration https://stackoverflow.com/a/66670818

2021-04-23 18:41 UTC, fjsj commented
> Persistence seems to be possible via Google Drive integration

In this case, we can leave the code that saves to Drive commented and put an explanation on the Notebook.

2021-04-27 14:54 UTC, rvlb commented on notebooks/google-colab/README.md
> +Deduplication Example | For when you have a single dirty dataset with duplicates | [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/githu
Please note that these urls consider the files already exist on main.

2021-04-29 14:26 UTC, fjsj approved these changes
LGTM

2021-04-29 14:26 UTC, merged